AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-nodejs-authentication-kit
Globals:
  Function:
    Timeout: 3

Resources:

  GetUserLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: getuser.handler
      Runtime: nodejs8.10
      Events:
        GetData:
          Type: Api
          Properties:
            Path: /user/{userId}
            Method: GET
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref authTableName

  PostUserLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: createuser.handler
      Runtime: nodejs8.10
      Events:
        PostData:
          Type: Api
          Properties:
            Path: /user
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref authTableName

  ValidateUserLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: createuser.handler
      Runtime: nodejs8.10
      Events:
        PostData:
          Type: Api
          Properties:
            Path: /user
            Method: POST
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref authTableName

  AuthTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        -
          AttributeName: "username"
          AttributeType: "S"
      KeySchema:
        -
          AttributeName: "username"
          KeyType: "String"
      ProvisionedThroughput:        ReadCapacityUnits: "5"
        WriteCapacityUnits: "5"
      TableName: !Ref authTableName
