openapi: 3.0.0
info:
  title: Create User API
  description: Creates a New User
  version: 1.0.0
servers:
  - url: /
    description: Send JSON to this URL to create a new user
paths:
  /user:
    post:
      summary: Returns a JSON Object with UserID.
      description: Creates a new User.
      requestBody:
        description: User Information to create
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserName"
            example:
              originalURL: google.com
        
      responses:
        '200':    # status code
          description: Successfully Added to DynamoDB
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/result"
              example:
                statusCode: 200
                # Parseable JSON
                body: "{userName: newUserName,
                      userID: 8675309}"
        '406':    # status code
          description: Error in method
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/result"
              examples:
                noData:
                  value:
                    statusCode: 406
                    body: "Error: No Data in Body"
                badData:
                  value:
                    statusCode: 406
                    body: "Error: Pass proper JSON"
        '500':    # status code
          description: Error in passing to DDB
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/result"
              example:
                statusCode: 500
                body: "Directly pass error from DDB SDK as JSON"
  /user/{userId}:
    get:
      summary: Retrieves a user by UserID
      description: Retrieves a UserName by UserID
      parameters:
        - name: UserName
          in: path
          required: true
          description: the user's UserId
          content:
            '*/*':
              schema:
                type: string
          
      responses:
        '301':    # status code
          description: Successfully Retrieved from DynamoDB 
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/result"
              example: 
                statusCode: 301
                headers: "{UserName: Bedtime4Bonzo}"
        '404':    # status code
          description: Provided UserID does not exist
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/result"
              example: 
                statusCode: 404
                body: "UserID Does Not Exist"
components:
  schemas:
    UserName:
      required:
        - UserName
        - email
      properties:
        UserName:
          type: string
        email:
          type: string
    result:
      required:
        - statusCode
        - body
      properties:
        statusCode:
          type: integer
        body:
          type: string
